# Generated by Django 3.0.6 on 2020-05-09 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
            preserve_default=False,
        ),
    ]
